name: bills_reminder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.0
  logging: ^1.3.0
  provider: ^6.1.2
  intl: ^0.18.0
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.4
  flutter_timezone: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true
